<?php

/**
 * @file
 * This module provides a set of fields that can be used to store
 * tabular data with a node.
 */

use Drupal\Core\Url;

/**
 * @todo should we create a helper function for sanitization?
 *  - we should see if it makes sense to sanitize on load as well as view
 */


/**
 * Implements hook_field_validate().
 */
function tablefield_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  drupal_add_css(drupal_get_path('module', 'tablefield') . '/tablefield.css');
  // Catch empty form submissions for required tablefields
  if ($instance['required'] && isset($items[0]) && tablefield_field_is_empty($items[0], $field)) {
    $message = t('@field is a required field.', array('@field' => $instance['label']));
    $errors[$field['field_name']][$langcode][0]['tablefield'][] = array(
      'error' => 'empty_required_tablefield',
      'message' => $message,
    );
  }
}


/**
 * Implements hook_theme().
 */
function tablefield_theme() {
  return array(
    'tablefield_view' => array(
      'function' => 'theme_tablefield_view',
      'variables' => array(
        'header' => NULL,
        'rows' => NULL,
        'delta' => NULL,
        'export' => NULL,
        'entity_type' => NULL,
        'entity_id' => NULL,
        'field_name' => NULL,
        'langcode' => NULL,
      ),
    ),
  );
}

/**
 * Theme function for table view
 */
function theme_tablefield_view($variables) {
  $render_array = array();

  // If the user has access to the csv export option, display it now.
  if ($variables['export'] && \Drupal::currentUser()->hasPermission('export tablefield')) {

    $route_params = ['entity_type', 'entity_id', 'field_name', 'langcode', 'delta'];
    $route_params = array_intersect_key($variables, array_flip($route_params));
    $url = Url::fromRoute('tablefield.export', $route_params);

    $render_array['export'] = array(
      '#type' => 'container',
      '#attributes' => array(
        'id' => 'tablefield-export-link-' . $variables['delta'],
        'class' => 'tablefield-export-link',
      ),
    );
    $render_array['export']['link'] = array(
      '#type' => 'link',
      '#title' => t('Export Table Data'),
      '#url' => $url,
    );
  }

  $render_array['tablefield'] = array(
    '#type' => 'table',
    '#header' => $variables['header'],
    '#rows' => $variables['rows'],
    '#attributes' => array(
      'id' => 'tablefield-' . $variables['delta'],
      'class' => array(
        'tablefield'
      ),
    ),
    '#prefix' => '<div id="tablefield-wrapper-' . $variables['delta'] . '" class="tablefield-wrapper">',
    '#sufix' => 'div',
  );

  return drupal_render($render_array);
}
